"""add_family_fields_to_memorial

Revision ID: 78df446128e1
Revises: add_qr_memorial_tables
Create Date: 2025-08-24 08:10:21.143169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78df446128e1'
down_revision = 'add_qr_memorial_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memorials', sa.Column('spouse_name', sa.String(length=200), nullable=True, comment='Name of spouse/husband/wife in Hebrew (optional)'))
    op.add_column('memorials', sa.Column('children_names', sa.Text(), nullable=True, comment='Names of children in Hebrew (optional)'))
    op.add_column('memorials', sa.Column('parents_names', sa.String(length=300), nullable=True, comment='Names of both parents in Hebrew (optional)'))
    op.add_column('memorials', sa.Column('family_names', sa.Text(), nullable=True, comment='Names of family members or family groups in Hebrew (optional)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memorials', 'family_names')
    op.drop_column('memorials', 'parents_names')
    op.drop_column('memorials', 'children_names')
    op.drop_column('memorials', 'spouse_name')
    # ### end Alembic commands ###