"""add_parent_name_hebrew

Revision ID: b9c506a8c889
Revises: add_memorial_fields
Create Date: 2025-08-15 16:14:24.847879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9c506a8c889'
down_revision = 'add_memorial_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='ID of the user who performed the action'),
    sa.Column('user_email', sa.String(length=255), nullable=True, comment='Email of the user who performed the action'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Type of action performed (create, update, delete, etc.)'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='Type of resource affected (user, memorial, photo, etc.)'),
    sa.Column('resource_id', sa.UUID(), nullable=True, comment='ID of the affected resource'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address of the client'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User agent string from the client'),
    sa.Column('request_id', sa.String(length=50), nullable=True, comment='Unique request identifier for correlation'),
    sa.Column('details', sa.JSON(), nullable=True, comment='Additional details about the action (JSON format)'),
    sa.Column('old_values', sa.JSON(), nullable=True, comment='Previous values before the action (for updates/deletes)'),
    sa.Column('new_values', sa.JSON(), nullable=True, comment='New values after the action (for creates/updates)'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Whether the action was successful'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if the action failed'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Duration of the action in milliseconds'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag - true if record is logically deleted'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_deleted'), 'audit_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_audit_logs_updated_at'), 'audit_logs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_email'), 'audit_logs', ['user_email'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('memorial_id', sa.UUID(), nullable=False, comment='ID of the memorial this contact belongs to'),
    sa.Column('contact_type', sa.Enum('EMAIL', 'WHATSAPP', name='contacttype'), nullable=False, comment='Type of contact (email or whatsapp)'),
    sa.Column('contact_value', sa.String(length=255), nullable=False, comment='Email address or phone number'),
    sa.Column('contact_name', sa.String(length=100), nullable=False, comment='Name of the contact person'),
    sa.Column('relationship_to_deceased', sa.String(length=100), nullable=True, comment='Relationship to the deceased (son, daughter, friend, etc.)'),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False, comment='Whether notifications are enabled for this contact'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether the contact has been verified (clicked confirmation link)'),
    sa.Column('verification_token', sa.String(length=255), nullable=True, comment='Token for contact verification'),
    sa.Column('verification_sent_at', sa.DateTime(), nullable=True, comment='When the verification message was sent'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='When the contact was verified'),
    sa.Column('yahrzeit_reminder_enabled', sa.Boolean(), nullable=False, comment='Whether to send yahrzeit reminders'),
    sa.Column('yahrzeit_reminder_days_before', sa.Integer(), nullable=False, comment='How many days before yahrzeit to send reminder'),
    sa.Column('memorial_updates_enabled', sa.Boolean(), nullable=False, comment='Whether to send memorial update notifications'),
    sa.Column('last_notification_sent_at', sa.DateTime(), nullable=True, comment='When the last notification was sent to this contact'),
    sa.Column('notification_count', sa.Integer(), nullable=False, comment='Total number of notifications sent to this contact'),
    sa.Column('bounce_count', sa.Integer(), nullable=False, comment='Number of bounced/failed notifications'),
    sa.Column('last_bounce_at', sa.DateTime(), nullable=True, comment='When the last bounce occurred'),
    sa.Column('is_bouncing', sa.Boolean(), nullable=False, comment='Whether this contact is currently bouncing (too many failures)'),
    sa.Column('added_by_user_id', sa.UUID(), nullable=True, comment='ID of the user who added this contact'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag - true if record is logically deleted'),
    sa.CheckConstraint('bounce_count >= 0', name='ck_contact_bounce_count_non_negative'),
    sa.CheckConstraint('notification_count >= 0', name='ck_contact_notification_count_non_negative'),
    sa.CheckConstraint('yahrzeit_reminder_days_before >= 0 AND yahrzeit_reminder_days_before <= 30', name='ck_contact_reminder_days_range'),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['memorial_id'], ['memorials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_index('ix_contact_bouncing', 'contacts', ['is_bouncing', 'bounce_count'], unique=False)
    op.create_index('ix_contact_memorial_enabled', 'contacts', ['memorial_id', 'notification_enabled'], unique=False)
    op.create_index('ix_contact_memorial_type', 'contacts', ['memorial_id', 'contact_type'], unique=False)
    op.create_index('ix_contact_memorial_value_unique', 'contacts', ['memorial_id', 'contact_value'], unique=True, postgresql_where='is_deleted = false')
    op.create_index('ix_contact_memorial_verified', 'contacts', ['memorial_id', 'is_verified'], unique=False)
    op.create_index('ix_contact_type_value', 'contacts', ['contact_type', 'contact_value'], unique=False)
    op.create_index('ix_contact_verification', 'contacts', ['verification_token'], unique=True, postgresql_where='verification_token IS NOT NULL')
    op.create_index(op.f('ix_contacts_contact_type'), 'contacts', ['contact_type'], unique=False)
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_is_bouncing'), 'contacts', ['is_bouncing'], unique=False)
    op.create_index(op.f('ix_contacts_is_deleted'), 'contacts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_contacts_is_verified'), 'contacts', ['is_verified'], unique=False)
    op.create_index(op.f('ix_contacts_memorial_id'), 'contacts', ['memorial_id'], unique=False)
    op.create_index(op.f('ix_contacts_notification_enabled'), 'contacts', ['notification_enabled'], unique=False)
    op.create_index(op.f('ix_contacts_updated_at'), 'contacts', ['updated_at'], unique=False)
    op.create_table('locations',
    sa.Column('memorial_id', sa.UUID(), nullable=False, comment='ID of the memorial this location belongs to'),
    sa.Column('cemetery_name', sa.String(length=200), nullable=False, comment='Name of the cemetery or burial ground'),
    sa.Column('cemetery_address', sa.String(length=500), nullable=True, comment='Full address of the cemetery'),
    sa.Column('cemetery_city', sa.String(length=100), nullable=True, comment='City where the cemetery is located'),
    sa.Column('cemetery_country', sa.String(length=100), nullable=True, comment='Country where the cemetery is located'),
    sa.Column('section', sa.String(length=100), nullable=True, comment='Section or area within the cemetery'),
    sa.Column('row', sa.String(length=50), nullable=True, comment='Row identifier within the section'),
    sa.Column('plot', sa.String(length=50), nullable=True, comment='Specific plot or grave number'),
    sa.Column('block', sa.String(length=50), nullable=True, comment='Block identifier (if applicable)'),
    sa.Column('gps_latitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='GPS latitude coordinate (decimal degrees)'),
    sa.Column('gps_longitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='GPS longitude coordinate (decimal degrees)'),
    sa.Column('gps_accuracy_meters', sa.Integer(), nullable=True, comment='GPS accuracy in meters'),
    sa.Column('directions_text', sa.Text(), nullable=True, comment='Written directions to find the grave'),
    sa.Column('directions_video_url', sa.String(length=500), nullable=True, comment='URL to a video showing directions to the grave'),
    sa.Column('landmark_description', sa.Text(), nullable=True, comment='Description of nearby landmarks or distinctive features'),
    sa.Column('grave_type', sa.String(length=50), nullable=True, comment='Type of grave (burial, mausoleum, columbarium, etc.)'),
    sa.Column('headstone_description', sa.Text(), nullable=True, comment='Description of the headstone or marker'),
    sa.Column('headstone_inscription', sa.Text(), nullable=True, comment='Text inscription on the headstone'),
    sa.Column('burial_permit_number', sa.String(length=100), nullable=True, comment='Official burial permit or certificate number'),
    sa.Column('plot_deed_number', sa.String(length=100), nullable=True, comment='Plot deed or ownership document number'),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False, comment='When the location information was last updated'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='When the location was last physically verified'),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True, comment='ID of the user who verified this location'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag - true if record is logically deleted'),
    sa.CheckConstraint('gps_accuracy_meters > 0', name='ck_location_gps_accuracy_positive'),
    sa.CheckConstraint('gps_latitude >= -90 AND gps_latitude <= 90', name='ck_location_latitude_range'),
    sa.CheckConstraint('gps_longitude >= -180 AND gps_longitude <= 180', name='ck_location_longitude_range'),
    sa.ForeignKeyConstraint(['memorial_id'], ['memorials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_location_cemetery_city', 'locations', ['cemetery_city'], unique=False)
    op.create_index('ix_location_cemetery_name', 'locations', ['cemetery_name'], unique=False)
    op.create_index('ix_location_gps_coordinates', 'locations', ['gps_latitude', 'gps_longitude'], unique=False, postgresql_where='gps_latitude IS NOT NULL AND gps_longitude IS NOT NULL')
    op.create_index('ix_location_last_updated', 'locations', ['last_updated_at'], unique=False)
    op.create_index('ix_location_plot_info', 'locations', ['section', 'row', 'plot'], unique=False)
    op.create_index('ix_location_verification', 'locations', ['verified_at', 'verified_by_user_id'], unique=False)
    op.create_index(op.f('ix_locations_cemetery_name'), 'locations', ['cemetery_name'], unique=False)
    op.create_index(op.f('ix_locations_created_at'), 'locations', ['created_at'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_is_deleted'), 'locations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_locations_memorial_id'), 'locations', ['memorial_id'], unique=True)
    op.create_index(op.f('ix_locations_updated_at'), 'locations', ['updated_at'], unique=False)
    op.create_table('notifications',
    sa.Column('memorial_id', sa.UUID(), nullable=True, comment='ID of the memorial this notification relates to (optional for system notifications)'),
    sa.Column('contact_id', sa.UUID(), nullable=True, comment='ID of the specific contact to notify (optional for broadcast notifications)'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='ID of the user this notification is for (optional)'),
    sa.Column('notification_type', sa.Enum('YAHRZEIT_REMINDER', 'MEMORIAL_UPDATE', 'SYSTEM', 'WELCOME', 'VERIFICATION_REMINDER', name='notificationtype'), nullable=False, comment='Type of notification'),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'SENT', 'FAILED', 'CANCELLED', 'RETRY', name='notificationstatus'), nullable=False, comment='Current status of the notification'),
    sa.Column('scheduled_date', sa.Date(), nullable=True, comment='Date when the notification should be sent'),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True, comment='Specific time when notification should be sent'),
    sa.Column('sent_date', sa.DateTime(timezone=True), nullable=True, comment='When the notification was actually sent'),
    sa.Column('delivered_date', sa.DateTime(timezone=True), nullable=True, comment='When the notification was delivered (if tracking available)'),
    sa.Column('opened_date', sa.DateTime(timezone=True), nullable=True, comment='When the notification was opened (if tracking available)'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of retry attempts made'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='Maximum number of retry attempts allowed'),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True, comment='When the next retry should be attempted'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if notification failed'),
    sa.Column('error_code', sa.String(length=50), nullable=True, comment='Error code for categorizing failures'),
    sa.Column('subject', sa.String(length=500), nullable=True, comment='Subject line for email notifications'),
    sa.Column('content', sa.JSON(), nullable=True, comment='Notification content as JSON (templates, variables, etc.)'),
    sa.Column('template_name', sa.String(length=100), nullable=True, comment='Name of the template to use for rendering'),
    sa.Column('delivery_channel', sa.String(length=20), nullable=True, comment='Channel used for delivery (email, whatsapp, etc.)'),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='External service ID for tracking (SendGrid message ID, etc.)'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Priority level (1=highest, 10=lowest)'),
    sa.Column('batch_id', sa.String(length=100), nullable=True, comment='ID for grouping notifications into batches'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag - true if record is logically deleted'),
    sa.CheckConstraint('max_retries >= 0', name='ck_notification_max_retries_non_negative'),
    sa.CheckConstraint('priority >= 1 AND priority <= 10', name='ck_notification_priority_range'),
    sa.CheckConstraint('retry_count >= 0', name='ck_notification_retry_count_non_negative'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memorial_id'], ['memorials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_batch', 'notifications', ['batch_id', 'status'], unique=False)
    op.create_index('ix_notification_contact_status', 'notifications', ['contact_id', 'status'], unique=False)
    op.create_index('ix_notification_delivery_tracking', 'notifications', ['sent_date', 'delivered_date', 'opened_date'], unique=False)
    op.create_index('ix_notification_memorial_type', 'notifications', ['memorial_id', 'notification_type'], unique=False)
    op.create_index('ix_notification_priority_pending', 'notifications', ['priority', 'created_at'], unique=False, postgresql_where="status IN ('pending', 'scheduled')")
    op.create_index('ix_notification_retry', 'notifications', ['status', 'next_retry_at'], unique=False, postgresql_where="status = 'retry'")
    op.create_index('ix_notification_scheduled', 'notifications', ['scheduled_date', 'scheduled_time'], unique=False, postgresql_where="status IN ('pending', 'scheduled')")
    op.create_index('ix_notification_status_type', 'notifications', ['status', 'notification_type'], unique=False)
    op.create_index('ix_notification_user_type', 'notifications', ['user_id', 'notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_batch_id'), 'notifications', ['batch_id'], unique=False)
    op.create_index(op.f('ix_notifications_contact_id'), 'notifications', ['contact_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_memorial_id'), 'notifications', ['memorial_id'], unique=False)
    op.create_index(op.f('ix_notifications_next_retry_at'), 'notifications', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_date'), 'notifications', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_time'), 'notifications', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_updated_at'), 'notifications', ['updated_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('memorials', 'owner_id',
               existing_type=sa.UUID(),
               comment='ID of the user who owns this memorial',
               existing_nullable=False)
    op.alter_column('memorials', 'deceased_name_hebrew',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False,
               comment='Name of the deceased in Hebrew')
    op.alter_column('memorials', 'deceased_name_english',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               comment='Name of the deceased in English (optional)',
               existing_nullable=True)
    op.alter_column('memorials', 'parent_name_hebrew',
               existing_type=sa.VARCHAR(length=100),
               comment='Name of parent (mother or father) in Hebrew',
               existing_nullable=False)
    op.alter_column('memorials', 'birth_date_gregorian',
               existing_type=sa.DATE(),
               comment='Birth date in Gregorian calendar',
               existing_nullable=True)
    op.alter_column('memorials', 'birth_date_hebrew',
               existing_type=sa.VARCHAR(length=50),
               comment='Birth date in Hebrew calendar (formatted string)',
               existing_nullable=True)
    op.alter_column('memorials', 'death_date_gregorian',
               existing_type=sa.DATE(),
               nullable=True,
               comment='Death date in Gregorian calendar')
    op.alter_column('memorials', 'death_date_hebrew',
               existing_type=sa.VARCHAR(length=50),
               comment='Death date in Hebrew calendar (formatted string)',
               existing_nullable=True)
    op.alter_column('memorials', 'yahrzeit_date_hebrew',
               existing_type=sa.VARCHAR(length=50),
               comment='Yahrzeit date in Hebrew calendar (11 months after death)',
               existing_nullable=True)
    op.alter_column('memorials', 'next_yahrzeit_gregorian',
               existing_type=sa.DATE(),
               comment='Next yahrzeit date in Gregorian calendar for reminders',
               existing_nullable=True)
    op.alter_column('memorials', 'biography',
               existing_type=sa.TEXT(),
               comment='Biography and life story of the deceased',
               existing_nullable=True)
    op.alter_column('memorials', 'memorial_song_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL to memorial song or audio file',
               existing_nullable=True)
    op.alter_column('memorials', 'is_locked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Whether the memorial is locked from editing',
               existing_nullable=False)
    op.alter_column('memorials', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Whether the memorial is publicly viewable',
               existing_nullable=False)
    op.alter_column('memorials', 'enable_comments',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Whether memorial comments are enabled',
               existing_nullable=False)
    op.alter_column('memorials', 'location_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Location latitude coordinate',
               existing_nullable=True)
    op.alter_column('memorials', 'location_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Location longitude coordinate',
               existing_nullable=True)
    op.alter_column('memorials', 'whatsapp_phones',
               existing_type=sa.TEXT(),
               comment='WhatsApp phone numbers for notifications (JSON array)',
               existing_nullable=True)
    op.alter_column('memorials', 'notification_emails',
               existing_type=sa.TEXT(),
               comment='Email addresses for notifications (JSON array)',
               existing_nullable=True)
    op.alter_column('memorials', 'page_views',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Number of times the memorial page has been viewed',
               existing_nullable=False)
    op.alter_column('memorials', 'unique_slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment='Unique URL slug for public memorial page access')
    op.alter_column('memorials', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment='Unique identifier for the record',
               existing_nullable=False)
    op.alter_column('memorials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memorials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memorials', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete flag - true if record is logically deleted',
               existing_nullable=False)
    op.drop_constraint('memorials_unique_slug_key', 'memorials', type_='unique')
    op.create_index('ix_memorial_death_date', 'memorials', ['death_date_gregorian'], unique=False, postgresql_where='death_date_gregorian IS NOT NULL')
    op.create_index('ix_memorial_name_search', 'memorials', ['deceased_name_hebrew', 'deceased_name_english'], unique=False)
    op.create_index('ix_memorial_owner_public', 'memorials', ['owner_id', 'is_public'], unique=False)
    op.create_index('ix_memorial_slug_public', 'memorials', ['unique_slug', 'is_public'], unique=False, postgresql_where='unique_slug IS NOT NULL')
    op.create_index('ix_memorial_yahrzeit', 'memorials', ['next_yahrzeit_gregorian'], unique=False, postgresql_where='next_yahrzeit_gregorian IS NOT NULL')
    op.create_index(op.f('ix_memorials_created_at'), 'memorials', ['created_at'], unique=False)
    op.create_index(op.f('ix_memorials_id'), 'memorials', ['id'], unique=False)
    op.create_index(op.f('ix_memorials_is_deleted'), 'memorials', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_memorials_is_locked'), 'memorials', ['is_locked'], unique=False)
    op.create_index(op.f('ix_memorials_is_public'), 'memorials', ['is_public'], unique=False)
    op.create_index(op.f('ix_memorials_next_yahrzeit_gregorian'), 'memorials', ['next_yahrzeit_gregorian'], unique=False)
    op.create_index(op.f('ix_memorials_owner_id'), 'memorials', ['owner_id'], unique=False)
    op.create_index(op.f('ix_memorials_unique_slug'), 'memorials', ['unique_slug'], unique=True)
    op.create_index(op.f('ix_memorials_updated_at'), 'memorials', ['updated_at'], unique=False)
    op.create_foreign_key(None, 'memorials', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('memorials', 'location')
    op.alter_column('photos', 'memorial_id',
               existing_type=sa.UUID(),
               comment='ID of the memorial this photo belongs to',
               existing_nullable=False)
    op.alter_column('photos', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Local file system path to the photo',
               existing_nullable=False)
    op.alter_column('photos', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Public URL to access the photo (CDN or static URL)',
               existing_nullable=True)
    op.alter_column('photos', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment='Original filename when uploaded',
               existing_nullable=False)
    op.alter_column('photos', 'photo_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Type of photo: deceased, grave, memorial1, memorial2, memorial3, memorial4',
               existing_nullable=False)
    op.alter_column('photos', 'caption',
               existing_type=sa.VARCHAR(length=500),
               comment='Optional caption or description for the photo',
               existing_nullable=True)
    op.alter_column('photos', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Display order for photos (1-6)',
               existing_nullable=False)
    op.alter_column('photos', 'file_size',
               existing_type=sa.INTEGER(),
               comment='File size in bytes',
               existing_nullable=True)
    op.alter_column('photos', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               comment='MIME type of the photo (image/jpeg, image/png, etc.)',
               existing_nullable=True)
    op.alter_column('photos', 'width',
               existing_type=sa.INTEGER(),
               comment='Image width in pixels',
               existing_nullable=True)
    op.alter_column('photos', 'height',
               existing_type=sa.INTEGER(),
               comment='Image height in pixels',
               existing_nullable=True)
    op.alter_column('photos', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Whether this is the primary/main photo for the memorial',
               existing_nullable=False)
    op.alter_column('photos', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Whether the photo is approved for display (content moderation)',
               existing_nullable=False)
    op.alter_column('photos', 'uploaded_by_user_id',
               existing_type=sa.UUID(),
               comment='ID of the user who uploaded this photo',
               existing_nullable=True)
    op.alter_column('photos', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='When the photo was uploaded',
               existing_nullable=False)
    op.alter_column('photos', 'is_processed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Whether the photo has been processed (resized, optimized, etc.)',
               existing_nullable=False)
    op.alter_column('photos', 'processing_error',
               existing_type=sa.VARCHAR(length=500),
               comment='Error message if photo processing failed',
               existing_nullable=True)
    op.alter_column('photos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment='Unique identifier for the record',
               existing_nullable=False)
    op.alter_column('photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('photos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('photos', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete flag - true if record is logically deleted',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment="User's email address (unique)",
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Hashed password using Werkzeug',
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment="User's first name",
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment="User's last name",
               existing_nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment="User's phone number",
               existing_nullable=True)
    op.alter_column('users', 'hebrew_name',
               existing_type=sa.VARCHAR(length=100),
               comment="User's Hebrew name (optional)",
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False,
               comment='Whether the user account is active')
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False,
               comment="Whether the user's email is verified")
    op.alter_column('users', 'verification_token',
               existing_type=sa.VARCHAR(length=255),
               comment='Token for email verification',
               existing_nullable=True)
    op.alter_column('users', 'reset_password_token',
               existing_type=sa.VARCHAR(length=255),
               comment='Token for password reset',
               existing_nullable=True)
    op.alter_column('users', 'reset_password_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Password reset token expiration time',
               existing_nullable=True)
    op.alter_column('users', 'subscription_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False,
               comment="User's subscription status")
    op.alter_column('users', 'subscription_end_date',
               existing_type=sa.DATE(),
               comment='When the subscription expires',
               existing_nullable=True)
    op.alter_column('users', 'trial_end_date',
               existing_type=sa.DATE(),
               comment='When the trial period ends',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False,
               comment="User's role for authorization")
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Last successful login timestamp',
               existing_nullable=True)
    op.alter_column('users', 'login_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False,
               comment='Total number of successful logins')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment='Unique identifier for the record',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='Record creation timestamp',
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='Record last update timestamp',
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False,
               comment='Soft delete flag - true if record is logically deleted')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index('ix_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('ix_user_reset_token', 'users', ['reset_password_token'], unique=True, postgresql_where='reset_password_token IS NOT NULL')
    op.create_index('ix_user_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index('ix_user_subscription_status', 'users', ['subscription_status', 'subscription_end_date'], unique=False)
    op.create_index('ix_user_verification_token', 'users', ['verification_token'], unique=True, postgresql_where='verification_token IS NOT NULL')
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_unique_constraint(None, 'users', ['reset_password_token'])
    op.create_unique_constraint(None, 'users', ['verification_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('ix_user_verification_token', table_name='users', postgresql_where='verification_token IS NOT NULL')
    op.drop_index('ix_user_subscription_status', table_name='users')
    op.drop_index('ix_user_role_active', table_name='users')
    op.drop_index('ix_user_reset_token', table_name='users', postgresql_where='reset_password_token IS NOT NULL')
    op.drop_index('ix_user_email_active', table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True,
               comment=None,
               existing_comment='Soft delete flag - true if record is logically deleted')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record last update timestamp',
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record creation timestamp',
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment=None,
               existing_comment='Unique identifier for the record',
               existing_nullable=False)
    op.alter_column('users', 'login_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True,
               comment=None,
               existing_comment='Total number of successful logins')
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Last successful login timestamp',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'user'::character varying"),
               nullable=True,
               comment=None,
               existing_comment="User's role for authorization")
    op.alter_column('users', 'trial_end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='When the trial period ends',
               existing_nullable=True)
    op.alter_column('users', 'subscription_end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='When the subscription expires',
               existing_nullable=True)
    op.alter_column('users', 'subscription_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'trial'::character varying"),
               nullable=True,
               comment=None,
               existing_comment="User's subscription status")
    op.alter_column('users', 'reset_password_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Password reset token expiration time',
               existing_nullable=True)
    op.alter_column('users', 'reset_password_token',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Token for password reset',
               existing_nullable=True)
    op.alter_column('users', 'verification_token',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Token for email verification',
               existing_nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True,
               comment=None,
               existing_comment="Whether the user's email is verified")
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True,
               comment=None,
               existing_comment='Whether the user account is active')
    op.alter_column('users', 'hebrew_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="User's Hebrew name (optional)",
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="User's phone number",
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="User's last name",
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="User's first name",
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Hashed password using Werkzeug',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="User's email address (unique)",
               existing_nullable=False)
    op.alter_column('photos', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete flag - true if record is logically deleted',
               existing_nullable=False)
    op.alter_column('photos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('photos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment=None,
               existing_comment='Unique identifier for the record',
               existing_nullable=False)
    op.alter_column('photos', 'processing_error',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Error message if photo processing failed',
               existing_nullable=True)
    op.alter_column('photos', 'is_processed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Whether the photo has been processed (resized, optimized, etc.)',
               existing_nullable=False)
    op.alter_column('photos', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='When the photo was uploaded',
               existing_nullable=False)
    op.alter_column('photos', 'uploaded_by_user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID of the user who uploaded this photo',
               existing_nullable=True)
    op.alter_column('photos', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='Whether the photo is approved for display (content moderation)',
               existing_nullable=False)
    op.alter_column('photos', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Whether this is the primary/main photo for the memorial',
               existing_nullable=False)
    op.alter_column('photos', 'height',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Image height in pixels',
               existing_nullable=True)
    op.alter_column('photos', 'width',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Image width in pixels',
               existing_nullable=True)
    op.alter_column('photos', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='MIME type of the photo (image/jpeg, image/png, etc.)',
               existing_nullable=True)
    op.alter_column('photos', 'file_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='File size in bytes',
               existing_nullable=True)
    op.alter_column('photos', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               comment=None,
               existing_comment='Display order for photos (1-6)',
               existing_nullable=False)
    op.alter_column('photos', 'caption',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Optional caption or description for the photo',
               existing_nullable=True)
    op.alter_column('photos', 'photo_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'memorial'::character varying"),
               comment=None,
               existing_comment='Type of photo: deceased, grave, memorial1, memorial2, memorial3, memorial4',
               existing_nullable=False)
    op.alter_column('photos', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Original filename when uploaded',
               existing_nullable=False)
    op.alter_column('photos', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Public URL to access the photo (CDN or static URL)',
               existing_nullable=True)
    op.alter_column('photos', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Local file system path to the photo',
               existing_nullable=False)
    op.alter_column('photos', 'memorial_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID of the memorial this photo belongs to',
               existing_nullable=False)
    op.add_column('memorials', sa.Column('location', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'memorials', type_='foreignkey')
    op.drop_index(op.f('ix_memorials_updated_at'), table_name='memorials')
    op.drop_index(op.f('ix_memorials_unique_slug'), table_name='memorials')
    op.drop_index(op.f('ix_memorials_owner_id'), table_name='memorials')
    op.drop_index(op.f('ix_memorials_next_yahrzeit_gregorian'), table_name='memorials')
    op.drop_index(op.f('ix_memorials_is_public'), table_name='memorials')
    op.drop_index(op.f('ix_memorials_is_locked'), table_name='memorials')
    op.drop_index(op.f('ix_memorials_is_deleted'), table_name='memorials')
    op.drop_index(op.f('ix_memorials_id'), table_name='memorials')
    op.drop_index(op.f('ix_memorials_created_at'), table_name='memorials')
    op.drop_index('ix_memorial_yahrzeit', table_name='memorials', postgresql_where='next_yahrzeit_gregorian IS NOT NULL')
    op.drop_index('ix_memorial_slug_public', table_name='memorials', postgresql_where='unique_slug IS NOT NULL')
    op.drop_index('ix_memorial_owner_public', table_name='memorials')
    op.drop_index('ix_memorial_name_search', table_name='memorials')
    op.drop_index('ix_memorial_death_date', table_name='memorials', postgresql_where='death_date_gregorian IS NOT NULL')
    op.create_unique_constraint('memorials_unique_slug_key', 'memorials', ['unique_slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('memorials', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete flag - true if record is logically deleted',
               existing_nullable=False)
    op.alter_column('memorials', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memorials', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memorials', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment=None,
               existing_comment='Unique identifier for the record',
               existing_nullable=False)
    op.alter_column('memorials', 'unique_slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment=None,
               existing_comment='Unique URL slug for public memorial page access')
    op.alter_column('memorials', 'page_views',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Number of times the memorial page has been viewed',
               existing_nullable=False)
    op.alter_column('memorials', 'notification_emails',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Email addresses for notifications (JSON array)',
               existing_nullable=True)
    op.alter_column('memorials', 'whatsapp_phones',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='WhatsApp phone numbers for notifications (JSON array)',
               existing_nullable=True)
    op.alter_column('memorials', 'location_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Location longitude coordinate',
               existing_nullable=True)
    op.alter_column('memorials', 'location_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Location latitude coordinate',
               existing_nullable=True)
    op.alter_column('memorials', 'enable_comments',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Whether memorial comments are enabled',
               existing_nullable=False)
    op.alter_column('memorials', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Whether the memorial is publicly viewable',
               existing_nullable=False)
    op.alter_column('memorials', 'is_locked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Whether the memorial is locked from editing',
               existing_nullable=False)
    op.alter_column('memorials', 'memorial_song_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL to memorial song or audio file',
               existing_nullable=True)
    op.alter_column('memorials', 'biography',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Biography and life story of the deceased',
               existing_nullable=True)
    op.alter_column('memorials', 'next_yahrzeit_gregorian',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Next yahrzeit date in Gregorian calendar for reminders',
               existing_nullable=True)
    op.alter_column('memorials', 'yahrzeit_date_hebrew',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Yahrzeit date in Hebrew calendar (11 months after death)',
               existing_nullable=True)
    op.alter_column('memorials', 'death_date_hebrew',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Death date in Hebrew calendar (formatted string)',
               existing_nullable=True)
    op.alter_column('memorials', 'death_date_gregorian',
               existing_type=sa.DATE(),
               nullable=False,
               comment=None,
               existing_comment='Death date in Gregorian calendar')
    op.alter_column('memorials', 'birth_date_hebrew',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Birth date in Hebrew calendar (formatted string)',
               existing_nullable=True)
    op.alter_column('memorials', 'birth_date_gregorian',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Birth date in Gregorian calendar',
               existing_nullable=True)
    op.alter_column('memorials', 'parent_name_hebrew',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Name of parent (mother or father) in Hebrew',
               existing_nullable=False)
    op.alter_column('memorials', 'deceased_name_english',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Name of the deceased in English (optional)',
               existing_nullable=True)
    op.alter_column('memorials', 'deceased_name_hebrew',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='Name of the deceased in Hebrew')
    op.alter_column('memorials', 'owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID of the user who owns this memorial',
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_updated_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_time'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_date'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_next_retry_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_memorial_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_contact_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_batch_id'), table_name='notifications')
    op.drop_index('ix_notification_user_type', table_name='notifications')
    op.drop_index('ix_notification_status_type', table_name='notifications')
    op.drop_index('ix_notification_scheduled', table_name='notifications', postgresql_where="status IN ('pending', 'scheduled')")
    op.drop_index('ix_notification_retry', table_name='notifications', postgresql_where="status = 'retry'")
    op.drop_index('ix_notification_priority_pending', table_name='notifications', postgresql_where="status IN ('pending', 'scheduled')")
    op.drop_index('ix_notification_memorial_type', table_name='notifications')
    op.drop_index('ix_notification_delivery_tracking', table_name='notifications')
    op.drop_index('ix_notification_contact_status', table_name='notifications')
    op.drop_index('ix_notification_batch', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_locations_updated_at'), table_name='locations')
    op.drop_index(op.f('ix_locations_memorial_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_is_deleted'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_created_at'), table_name='locations')
    op.drop_index(op.f('ix_locations_cemetery_name'), table_name='locations')
    op.drop_index('ix_location_verification', table_name='locations')
    op.drop_index('ix_location_plot_info', table_name='locations')
    op.drop_index('ix_location_last_updated', table_name='locations')
    op.drop_index('ix_location_gps_coordinates', table_name='locations', postgresql_where='gps_latitude IS NOT NULL AND gps_longitude IS NOT NULL')
    op.drop_index('ix_location_cemetery_name', table_name='locations')
    op.drop_index('ix_location_cemetery_city', table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_contacts_updated_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_notification_enabled'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_memorial_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_verified'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_deleted'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_bouncing'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_type'), table_name='contacts')
    op.drop_index('ix_contact_verification', table_name='contacts', postgresql_where='verification_token IS NOT NULL')
    op.drop_index('ix_contact_type_value', table_name='contacts')
    op.drop_index('ix_contact_memorial_verified', table_name='contacts')
    op.drop_index('ix_contact_memorial_value_unique', table_name='contacts', postgresql_where='is_deleted = false')
    op.drop_index('ix_contact_memorial_type', table_name='contacts')
    op.drop_index('ix_contact_memorial_enabled', table_name='contacts')
    op.drop_index('ix_contact_bouncing', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_email'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_updated_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_deleted'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###