"""Add location, contacts and enable_comments fields to memorials

Revision ID: add_memorial_fields
Revises: 76791300ffe7
Create Date: 2025-08-12 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_memorial_fields'
down_revision: Union[str, None] = '76791300ffe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memorials', sa.Column('enable_comments', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('memorials', sa.Column('location', sa.String(length=500), nullable=True))
    op.add_column('memorials', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('memorials', sa.Column('location_lng', sa.Float(), nullable=True))
    op.add_column('memorials', sa.Column('whatsapp_phones', sa.Text(), nullable=True))
    op.add_column('memorials', sa.Column('notification_emails', sa.Text(), nullable=True))
    
    # Create indexes for new fields
    op.create_index(op.f('ix_memorials_enable_comments'), 'memorials', ['enable_comments'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memorials_enable_comments'), table_name='memorials')
    op.drop_column('memorials', 'notification_emails')
    op.drop_column('memorials', 'whatsapp_phones')
    op.drop_column('memorials', 'location_lng')
    op.drop_column('memorials', 'location_lat')
    op.drop_column('memorials', 'location')
    op.drop_column('memorials', 'enable_comments')
    # ### end Alembic commands ###